Insert into KeySignatures values (1,'C','A','None','None')
Insert into KeySignatures values (2,'G','E','F#','Sharps')
Insert into KeySignatures values (3,'D','B','F# C#','Sharps')
Insert into KeySignatures values (4,'A','F#','F# C# G#','Sharps')
Insert into KeySignatures values (5,'E','C#','F# C# G# D#','Sharps')
Insert into KeySignatures values (6,'B','G#','F# C# G# D# A#','Enharmonic')
Insert into KeySignatures values (7,'F#','D#','F# C# G# D# A# E#','Enharmonic')
Insert into KeySignatures values (8,'C#','A#','F# C# G# D# A# E# B#','Enharmonic')
Insert into KeySignatures values (9,'F','D','Bb','Flats')
Insert into KeySignatures values (10,'Bb','G','Bb Eb','Flats')
Insert into KeySignatures values (11,'Eb','C','Bb Eb Ab','Flats')
Insert into KeySignatures values (12,'Ab','F','Bb Eb Ab Db','Flats')
Insert into KeySignatures values (13,'Db','Bb','Bb Eb Ab Db Gb','Enharmonic')
Insert into KeySignatures values (14,'Gb','Eb','Bb Eb Ab Db Gb Cb','Enharmonic')
Insert into KeySignatures values (15,'Cb','Ab','Bb Eb Ab Db Gb Cb Fb','Enharmonic')

