Insert into Scales values (1,'C','1','C D E F G A B C')
Insert into Scales values (2,'G','1','G A B C D E F# G')
Insert into Scales values (3,'D','1','D E F# G A B C# D')
Insert into Scales values (4,'A','1','A B C# D E F# G# A')
Insert into Scales values (5,'E','1','E F# G# A B C# D# E')
Insert into Scales values (6,'B','1','B C# D# E F# G# A# B')
Insert into Scales values (7,'F#','1','F# G# A# B C# D# E# F#')
Insert into Scales values (8,'C#','1','C# D# E# F# G# A# B# C#')
Insert into Scales values (9,'F','1','F G A Bb C D E F')
Insert into Scales values (10,'Bb','1','Bb C D Eb F G A Bb')
Insert into Scales values (11,'Eb','1','Eb F G Ab Bb C D Eb')
Insert into Scales values (12,'Ab','1','Ab Bb C Db Eb F G Ab')
Insert into Scales values (13,'Db','1','Db Eb F Gb Ab Bb C Db')
Insert into Scales values (14,'Gb','1','Gb Ab Bb Cb Db Eb F Gb')
Insert into Scales values (15,'Cb','1','Cb Db Eb Fb Gb Ab Bb Cb')
Insert into Scales values (16,'A','2','A B C D E F G# A')
Insert into Scales values (17,'E','2','E F# G A B C D# E')
Insert into Scales values (18,'B','2','B C# D E F# G A# B')
Insert into Scales values (19,'F#','2','F# G# A B C# D E# F#')
Insert into Scales values (20,'C#','2','C# D# E F# G# A B# C#')
Insert into Scales values (21,'G#','2','')
Insert into Scales values (22,'D#','2','')
Insert into Scales values (23,'A#','2','')
Insert into Scales values (24,'D','2','')
Insert into Scales values (25,'G','2','G A Bb C D Eb F# G')
Insert into Scales values (26,'C','2','C D Eb F G Ab B C')
Insert into Scales values (27,'F','2','')
Insert into Scales values (28,'Bb','2','Bb C Db Eb F Gb A Bb')
Insert into Scales values (29,'Eb','2','Eb F Gb Ab Bb Cb D Eb')
Insert into Scales values (30,'Ab','2','')
Insert into Scales values (31,'A','3','A B C D E F# G# A, A B C D E F G A')
Insert into Scales values (32,'E','3','E F# G A B C# D# E, E F# G A B C D E')
Insert into Scales values (33,'B','3','B C# D E F# G# A# B, B C# D E F# G A B')
Insert into Scales values (34,'F#','3','F# G# A B C# D# E# F#, F# G# A B C# D E F#')
Insert into Scales values (35,'C#','3','C# D# E F# G# A B# C#')
Insert into Scales values (36,'G#','3','')
Insert into Scales values (37,'D#','3','')
Insert into Scales values (38,'A#','3','')
Insert into Scales values (39,'D','3','')
Insert into Scales values (40,'G','3','G A Bb C D E F# G, G A Bb C D Eb F G')
Insert into Scales values (41,'C','3','C D Eb F G A B C, C D Eb F G Ab Bb C')
Insert into Scales values (42,'F','3','TBD')
Insert into Scales values (43,'Bb','3','Bb C Db Eb F G A Bb , Bb C Db Eb F Gb Ab Bb')
Insert into Scales values (44,'Eb','3','Eb F Gb Ab Bb C D Eb, Eb F Gb Ab Bb Cb Db Eb')
Insert into Scales values (45,'Ab','3','TBD')
Insert into Scales values (46,'A','','A B C D E F G A')
Insert into Scales values (47,'E','','E F# G A B C D E')
Insert into Scales values (48,'B','','B C# D E F# G A B')
Insert into Scales values (49,'F#','','F# G# A B C# D E F#')
Insert into Scales values (50,'C#','','C# D# E F# G# A B C#')
Insert into Scales values (51,'G#','','TBD')
Insert into Scales values (52,'D#','','TBD')
Insert into Scales values (53,'A#','','TBD')
Insert into Scales values (54,'D','','TBD')
Insert into Scales values (55,'G','','G A Bb C D Eb F G')
Insert into Scales values (56,'C','','C D Eb F G Ab Bb C')
Insert into Scales values (57,'F','','TBD')
Insert into Scales values (58,'Bb','','Bb C Db Eb F Gb Ab Bb')
Insert into Scales values (59,'Eb','','Eb F Gb Ab Bb Cb Db Eb')
Insert into Scales values (60,'Ab','','TBD')
